#!/usr/bin/env bash
# Register dockur Windows guests as hub Ansible targets (kind=target). No spoke join.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
# shellcheck source=lib.sh
source "$ROOT/scripts/lib.sh"

lab_compose_cmd
lab_load_windows_env
lab_compose_files_windows

echo "== hub must be up =="
lab_run_hub ansible-flow-mcp hub status >/dev/null

# Pass lab password into hub only for this enroll (not committed).
lab_run_hub bash -lc "
  set -e
  export WIN_USERNAME='${WIN_USERNAME}'
  export WIN_PASSWORD='${WIN_PASSWORD}'
  python3 <<'PY'
from __future__ import annotations

import os
from pathlib import Path

from ansible_flow_mcp.hub.enroll import (
    create_group_op,
    hub_status,
    register_target,
    set_group_members_op,
    update_target_node,
)
from ansible_flow_mcp.hub.state import load_hub_state
from ansible_flow_mcp.paths import hub_dir

user = os.environ.get('WIN_USERNAME') or 'Docker'
password = os.environ.get('WIN_PASSWORD') or 'admin'
st = load_hub_state(hub_dir())

targets = [
    {
        'name': 'win-client',
        'host': 'win-client',
        'port': 5985,
        'labels': {'mesh_os': 'windows-11', 'mesh_label': 'win-client', 'mesh_tier': 'windows'},
    },
    {
        'name': 'win-server',
        'host': 'win-server',
        'port': 5985,
        'labels': {'mesh_os': 'windows-2022', 'mesh_label': 'win-server', 'mesh_tier': 'windows'},
    },
]

status = hub_status(state=st)
existing = set(status.get('targets') or [])
spokes = set(status.get('spokes') or [])

for t in targets:
    name = t['name']
    if name in spokes:
        raise SystemExit(f'{name} is already a spoke — refuse to register as target')
    if name in existing:
        print(f'update existing target {name}')
        update_target_node(
            name,
            ansible_host=t['host'],
            ansible_port=t['port'],
            ansible_user=user,
            ansible_connection='winrm',
            extra={
                'ansible_winrm_transport': 'ntlm',
                'ansible_winrm_server_cert_validation': 'ignore',
                'ansible_winrm_scheme': 'http',
                'ansible_flow_labels': t['labels'],
            },
            state=st,
        )
    else:
        print(f'register target {name}')
        try:
            register_target(
                name,
                ansible_host=t['host'],
                ansible_connection='winrm',
                ansible_port=t['port'],
                ansible_user=user,
                extra={
                    'ansible_winrm_transport': 'ntlm',
                    'ansible_winrm_server_cert_validation': 'ignore',
                    'ansible_winrm_scheme': 'http',
                    'ansible_flow_labels': t['labels'],
                },
                state=st,
            )
        except ValueError as exc:
            if 'already registered' in str(exc):
                update_target_node(
                    name,
                    ansible_host=t['host'],
                    ansible_port=t['port'],
                    ansible_user=user,
                    ansible_connection='winrm',
                    state=st,
                )
            else:
                raise

    # Secrets stay in host_vars (0600), never in inventory.yml / MCP responses
    hv_dir = st.root / 'host_vars'
    hv_dir.mkdir(parents=True, exist_ok=True)
    hv = hv_dir / f'{name}.yml'
    hv.write_text(
        f'# lab-only — generated by enroll-windows.sh\\n'
        f'ansible_user: {user!r}\\n'
        f'ansible_password: {password!r}\\n'
        f'ansible_connection: winrm\\n'
        f'ansible_winrm_transport: ntlm\\n'
        f'ansible_winrm_scheme: http\\n'
        f'ansible_winrm_server_cert_validation: ignore\\n'
        f'ansible_port: {t[\"port\"]}\\n',
        encoding='utf-8',
    )
    try:
        os.chmod(hv, 0o600)
    except OSError:
        pass
    print(f'  host_vars -> {hv}')

# Groups
for gname, members in (
    ('windows', ['win-client', 'win-server']),
    ('win-clients', ['win-client']),
    ('win-servers', ['win-server']),
):
    try:
        create_group_op(gname, state=st)
    except ValueError as exc:
        if 'already exists' not in str(exc):
            raise
    # merge with any existing members of other kinds
    from ansible_flow_mcp.hub.inventory import list_groups, load_inventory

    inv = load_inventory(st.inventory_path)
    cur = []
    for g in list_groups(inv):
        if g['name'] == gname:
            cur = list(g['hosts'])
            break
    merged = sorted(set(cur) | set(members))
    set_group_members_op(gname, merged, state=st)
    print(f'group {gname}: {merged}')

final = hub_status(state=st)
print('targets:', final.get('targets'))
print('ENROLL WINDOWS OK')
PY
"

echo ""
echo "Windows targets registered. Run ./scripts/smoke-windows.sh"
lab_run_hub ansible-flow-mcp hub status
